import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/tax_transaction.dart';
import 'form_summary.dart';

/// Generates a prepopulated Schedule C / Schedule A *worksheet* PDF.
///
/// This is a summary worksheet, not an official IRS filing. It maps the user's
/// recorded totals onto the real form line numbers so the figures can be
/// transcribed onto a return (or sanity-checked against tax software).
class FormPdfService {
  final NumberFormat _money = NumberFormat.currency(symbol: r'$');
  final DateFormat _dateFmt = DateFormat.yMMMMd();

  Future<Uint8List> buildWorksheet(
    List<TaxTransaction> transactions,
    int taxYear, {
    String? taxpayerName,
  }) async {
    final scheduleC = ScheduleCSummary.from(transactions, taxYear);
    final scheduleA = ScheduleASummary.from(transactions, taxYear);

    final doc = pw.Document(
      title: 'Tax worksheet $taxYear',
      author: 'Taxes Helper',
    );

    final generated = _dateFmt.format(DateTime.now());

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.all(36),
        footer: (context) => _footer(context),
        build: (context) => [
          _docHeader(taxYear, taxpayerName, generated),
          pw.SizedBox(height: 12),
          ..._scheduleC(scheduleC),
          if (scheduleA.hasData) ...[
            pw.SizedBox(height: 24),
            ..._scheduleA(scheduleA),
          ],
          pw.SizedBox(height: 16),
          _disclaimer(),
        ],
      ),
    );

    return doc.save();
  }

  // ---------------------------------------------------------------------------

  pw.Widget _docHeader(int taxYear, String? name, String generated) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Tax Year $taxYear - Worksheet',
            style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 2),
        if (name != null && name.isNotEmpty)
          pw.Text('Taxpayer: $name', style: const pw.TextStyle(fontSize: 11)),
        pw.Text('Generated by Taxes Helper on $generated',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
      ],
    );
  }

  List<pw.Widget> _scheduleC(ScheduleCSummary s) {
    return [
      _sectionTitle('Schedule C - Profit or Loss From Business'),
      _partTitle('Part I - Income'),
      _line('1', 'Gross receipts or sales', s.grossReceipts),
      _line('2', 'Returns and allowances', s.returnsAllowances),
      _line('3', 'Subtract line 2 from line 1', s.netReceipts, subtotal: true),
      _line('4', 'Cost of goods sold (from line 42)', s.costOfGoodsSold),
      _line('5', 'Gross profit (line 3 - line 4)', s.grossProfit,
          subtotal: true),
      _line('6', 'Other income', s.otherIncome),
      _line('7', 'Gross income (line 5 + line 6)', s.grossIncome, total: true),
      pw.SizedBox(height: 10),
      _partTitle('Part II - Expenses'),
      ...s.expenses.map((e) => _line(
            e.lineRef.replaceAll('Line ', ''),
            e.label,
            e.amount,
          )),
      _line('28', 'Total expenses', s.totalExpenses, subtotal: true),
      _line('29', 'Tentative profit (line 7 - line 28)', s.tentativeProfit,
          subtotal: true),
      _line('30', 'Expenses for business use of home', 0,
          note: 'not tracked'),
      _line('31', 'Net profit or (loss)', s.netProfit, total: true),
      if (s.costOfGoodsSold != 0) ...[
        pw.SizedBox(height: 10),
        _partTitle('Part III - Cost of Goods Sold'),
        _line('36', 'Purchases', s.costOfGoodsSold),
        _line('42', 'Cost of goods sold (enter on line 4)', s.costOfGoodsSold,
            total: true),
      ],
    ];
  }

  List<pw.Widget> _scheduleA(ScheduleASummary s) {
    return [
      _sectionTitle('Schedule A - Itemized Deductions'),
      ...s.items.map((e) => _line(
            e.lineRef.replaceAll('Line ', ''),
            e.label,
            e.amount,
          )),
      _line('', 'Total itemized deductions (before IRS limits)', s.total,
          total: true),
      pw.SizedBox(height: 6),
      pw.Text(
        'Note: amounts are raw totals. Real Schedule A applies limits - e.g. '
        'medical exceeding 7.5% of AGI, and the \$10,000 cap on state and '
        'local taxes (SALT). Apply these in your tax software.',
        style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
      ),
    ];
  }

  // ---------------------------------------------------------------------------

  pw.Widget _sectionTitle(String text) {
    return pw.Container(
      width: double.infinity,
      margin: const pw.EdgeInsets.only(top: 4, bottom: 6),
      padding: const pw.EdgeInsets.symmetric(vertical: 4, horizontal: 6),
      color: PdfColors.blueGrey800,
      child: pw.Text(text,
          style: pw.TextStyle(
              color: PdfColors.white,
              fontSize: 13,
              fontWeight: pw.FontWeight.bold)),
    );
  }

  pw.Widget _partTitle(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(top: 6, bottom: 2),
      child: pw.Text(text,
          style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
    );
  }

  pw.Widget _line(
    String ref,
    String label,
    double amount, {
    bool subtotal = false,
    bool total = false,
    String? note,
  }) {
    final weight = (subtotal || total) ? pw.FontWeight.bold : pw.FontWeight.normal;
    return pw.Container(
      decoration: total
          ? const pw.BoxDecoration(
              border: pw.Border(
                top: pw.BorderSide(color: PdfColors.grey400),
                bottom: pw.BorderSide(color: PdfColors.grey400),
              ),
            )
          : const pw.BoxDecoration(
              border:
                  pw.Border(bottom: pw.BorderSide(color: PdfColors.grey200)),
            ),
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 26,
            child: pw.Text(ref,
                style: pw.TextStyle(fontSize: 9, fontWeight: weight)),
          ),
          pw.Expanded(
            child: pw.Text(
              note == null ? label : '$label  ($note)',
              style: pw.TextStyle(fontSize: 10, fontWeight: weight),
            ),
          ),
          pw.Text(_money.format(amount),
              style: pw.TextStyle(fontSize: 10, fontWeight: weight)),
        ],
      ),
    );
  }

  pw.Widget _disclaimer() {
    return pw.Container(
      padding: const pw.EdgeInsets.all(8),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Text(
        'This worksheet is a bookkeeping summary, NOT a filed tax form and NOT '
        'tax advice. Figures are based solely on the transactions you entered. '
        'Verify everything in your tax software and consult a tax professional '
        'before filing.',
        style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey800),
      ),
    );
  }

  pw.Widget _footer(pw.Context context) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(top: 6),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Taxes Helper worksheet',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
        ],
      ),
    );
  }
}
